### ISSUE TITLE
🐛 Bug Report: Resolving dependencies on device_info_plus

### ISSUE THREAD

**Issue by MrFantuk** [appwrite/sdk-for-flutter#150]
### 👟 Reproduction steps

When I launching project with pub spec:

appwrite: ^9.0.0
flutter_quill: ^7.2.0

### 👍 Expected behavior

Upgrade dependencies with latest versions

### 👎 Actual Behavior

Resolving dependencies...
Because flutter_quill >=7.1.17+1 depends on device_info_plus ^9.0.0 and appwrite 9.0.0 depends on device_info_plus ^8.1.0, flutter_quill >=7.1.17+1 is incompatible with appwrite 9.0.0.
And because no versions of appwrite match >9.0.0 <10.0.0, flutter_quill >=7.1.17+1 is incompatible with appwrite ^9.0.0.
So, because stomhelp depends on both appwrite ^9.0.0 and flutter_quill ^7.2.0, version solving failed.
exit code 1

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@MrFantuk this is simply an issue with dependency conflict. One way to resolve this issue is to add a `dependency_overrides` as the following

```yaml
dependency_overrides:
	device_info_plus: 9.0.0
```

Or another way to use the version of `flutter_quill` that uses the same version of device_info_plus as appwrite. Or the wait for Appwrite SDK to update with newer version of `device_info_plus` as we will be publishing updates soon.

Please let us know if this solves your issue, or not.

Thank you

**Comment by MrFantuk** [comment]
As a temporary fix, that's work, but it could occur bugs on using overrides. Any way, waiting for updates. Thank you)

**Comment by lohanidamodar** [comment]
@MrFantuk the new Appwrite SDK version 9.0.1 should no longer have this issue. Feel free to re-open the issue if you still have problems.
