### ISSUE TITLE
getFilePreview() not returning a Future

### ISSUE THREAD

**Issue by PsychTechApS** [appwrite/sdk-for-flutter#7]
In Flutter I am working on a storage list page. 

To preview the file/icon i am about to use getFilePreview(). How come this is not returning a future? It is just returning a String. I would expect it to return Future<Response> like fx. getFile() ?

This is also the case for: getFileDownload() and getFileView()

**Comment by eldadfux** [comment]
@lohanidamodar what do you think about this? It relates to the credentials headers issue we talked about for the image widget.

**Comment by lohanidamodar** [comment]
@eldadfux this is not related to the credentials headers issues.
@PsychTechApS the functions that you are talking about `getFilePreview()`, `getFileDownload()` and `getFileView()` are just constructing the URL for the required function, so they return the String (url) instead of future. Using the url, in preview you can display the image preview.

However, there is still one issue, if you file doesn't have public read permission, right now there is no way to access the URL previews.

I am not sure why you need or want Future?

**Comment by eldadfux** [comment]
@lohanidamodar both issues have similarities because of the read permission problem, we need to find a similar solution to all.

Would it be better to keep returning a URL and expose another method to get Appwrite credentials headers in order to have the flexibility of showing this resources using other widgets (like the image widget) with an HTTP call made by native or any other HTTP client, or should we return a promise with the file contents and allow to load it using a different method into 3rd party widgets (loading with a content string vs. loading with a URL)?

**Comment by lohanidamodar** [comment]
@eldadfux If we do return the file content instead of url+credentials, we need ways to handle downloads, manage cache implemented in appwrite SDK, but I believe instead of making assumptions and implementing details, we should simply return the Url and some method for credentials, so everyone have flexibility to use their own way of downloads, caching..

**Comment by PsychTechApS** [comment]
@lohanidamodar So these functions just construct a url-string without calling the api and that is why there is no latency? I see. 

In the dart doc comments (///) and the api documents, would it be possible to write the result type in the text? And when it is a json result, the different var types?

I understand, that right now all files need to be public accesible to be downloaded this way, which of cause is a no go.
To return the file would fix this problem, and would be expected behaviour for a flutter developer when a fuction is named getFile() - otherwise I think it should have been named getFileURL(). Cache managment could be up to the dev to implement.

**Comment by lohanidamodar** [comment]
Yes, I believe the names you are suggesting seems appropriate. However if we want allow devs to be able to manage the downloading and caching themselves, instead of appwrite returning content, it's best to keep urls, and provide access to authentication tokens/cookies required.
@PsychTechApS Also, I believe with appwrite 0.7 we will have proper response objects documented as well. 
cc @eldadfux

**Comment by eldadfux** [comment]
The 0.7 release will allow us to generate the response object docs, they will probably be available shortly after.

**Comment by eldadfux** [comment]
Appwrite Flutter SDK v0.4.0-dev.2 now returns a Future for `getFilePreview()`

https://pub.dev/packages/appwrite/versions/0.4.0-dev.2

@PsychTechApS please feel free to test it out and share any feedback you might have.

**Comment by eldadfux** [comment]
This fix is now part of v0.4.0 which is out of dev channel
